"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'salary.png',
        'plist': {'CFBundleShortVersionString':'0.1.0'},
}

setup(
    app=APP,
    name='Brutto-Netto-Salary',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
